import type { Client, Visit } from './types'

const report = 'https://vanessarodriguesbr.github.io/painelchamados/'
const base = { status:'Renovado', ticketReportUrl:report, trelloUrl:null, misuseHistory:'Não', training:'Não' } as const

export const demoClients: Client[] = [
  { ...base,id:'c1',sheetRow:10,startDateFormatted:'12/01/2022',endDateFormatted:'12/01/2027',contractNumber:'2021-000323',legalName:'CONDOMÍNIO HORIZON SHOPPING',siteName:'Horizon Shopping',administrator:'Grupo Aurora',segment:'Shopping',quantity:4,contractValue:6114,state:'AM',accountManager:'Janderson Souza',relationship:'Excelente',financial:'Adimplente',sla:'72hrs corridas',misuseHistory:'Sim',logisticsComplexity:'Alto',lastContact:'12 set 2026',address:'Av. Central, 1300 — Manaus, AM',contact:{name:'Elissandra Dourado',role:'Operações',phone:'(92) 98214-1898',email:'elissandra@cliente.com.br'}},
  { ...base,id:'c2',sheetRow:15,startDateFormatted:'23/08/2021',endDateFormatted:'23/08/2027',contractNumber:'2021-000289',legalName:'GR SERVIÇOS INTEGRADOS LTDA',siteName:'Hangar Business Park',administrator:'Orgânico',segment:'Condomínio',quantity:1,contractValue:1871.62,state:'BA',accountManager:'Vinícius Gaspar',relationship:'Sensível',financial:'Inadimplente Crítico',sla:'72hrs úteis',logisticsComplexity:'Médio',lastContact:'08 set 2026',address:'Av. Luís Viana Filho — Salvador, BA',contact:{name:'Diego Dias Viana',role:'Comprador',phone:'(11) 97875-4702',email:'diego@cliente.com.br'}},
  { ...base,id:'c3',sheetRow:4,startDateFormatted:'29/08/2025',endDateFormatted:'29/08/2027',contractNumber:'2025-20274',legalName:'GR ADMINISTRAÇÃO PATRIMONIAL',siteName:'Condomínio O Parque',administrator:'Manager Gestão',segment:'Condomínio',quantity:1,contractValue:1890,state:'SP',accountManager:'Brandon David',relationship:'Sensível',financial:'Inadimplente Crítico',sla:'48hrs úteis',misuseHistory:'Sim',logisticsComplexity:'Baixo',training:'Sim',lastContact:'04 set 2026',address:'São Paulo, SP',contact:{name:'Diego Dias Viana',role:'Comprador',phone:'(11) 97875-4702',email:'diego@cliente.com.br'}},
  { ...base,id:'c4',sheetRow:9,startDateFormatted:'04/07/2025',endDateFormatted:'04/07/2027',contractNumber:'2025-20263',legalName:'AMAZONAS CENTRO COMERCIAL',siteName:'Amazonas Shopping',administrator:'Allos',segment:'Shopping',quantity:2,contractValue:3057,state:'AM',accountManager:'Janderson Souza',relationship:'Excelente',financial:'Inadimplente Crítico',sla:'72hrs corridas',logisticsComplexity:'Alto',lastContact:'29 ago 2026',address:'Manaus, AM',contact:{name:'Roberto Bahia',role:'Operações',phone:'(92) 98214-1898',email:'roberto@cliente.com.br'}},
  { ...base,id:'c5',sheetRow:11,startDateFormatted:'08/11/2022',endDateFormatted:'08/11/2027',contractNumber:'2022-367',legalName:'MAP SERVIÇOS DE SEGURANÇA',siteName:'Aeroporto Salvador',administrator:'VINCI Airports',segment:'Aeroporto',quantity:1,contractValue:1987.76,state:'BA',accountManager:'Vinícius Gaspar',relationship:'Excelente',financial:'Adimplente',sla:'Sem menção',logisticsComplexity:'Médio',lastContact:'15 set 2026',address:'Salvador, BA',contact:{name:'Jeovan Barboza',role:'Coordenador Administrativo',phone:'(71) 99937-0667',email:'jeovan@cliente.com.br'}},
  { ...base,id:'c6',sheetRow:8,startDateFormatted:'19/04/2019',endDateFormatted:'19/04/2027',contractNumber:'2019-139',legalName:'CONDOMÍNIO VIA VERDE',siteName:'Via Verde Shopping',administrator:'Alqia',segment:'Shopping',quantity:1,contractValue:2230.22,state:'AC',accountManager:'Carpineli',relationship:'Excelente',financial:'Adimplente',sla:'72hrs úteis',logisticsComplexity:'Alto',lastContact:'10 set 2026',address:'Rio Branco, AC',contact:{name:'Jonivaldo Moreira',role:'Operações',phone:'(68) 98115-8115',email:'jonivaldo@cliente.com.br'}},
  { ...base,id:'c7',sheetRow:14,startDateFormatted:'04/10/2021',endDateFormatted:'04/10/2027',contractNumber:'2021-000293',legalName:'BOULEVARD CENTRO COMERCIAL',siteName:'Boulevard Feira',administrator:'Allos',segment:'Shopping',quantity:1,contractValue:1528.5,state:'BA',accountManager:'Evan Cleyton',relationship:'Crítico',financial:'Inadimplência Moderada',sla:'72hrs corridas',logisticsComplexity:'Médio',lastContact:'21 ago 2026',address:'Feira de Santana, BA',contact:{name:'Caio Gama',role:'Gerente de Operações',phone:'(75) 3617-3029',email:'caio@cliente.com.br'}},
  { ...base,id:'c8',sheetRow:7,startDateFormatted:'23/09/2022',endDateFormatted:'23/09/2027',contractNumber:'2022-362',legalName:'VIA QUATRO MOBILIDADE',siteName:'Via Quatro',administrator:'Motiva Trilhos',segment:'Metrô',quantity:2,contractValue:3910.88,state:'SP',accountManager:'Brandon David',relationship:'Excelente',financial:'Adimplente',sla:'48hrs corridas',misuseHistory:'Sim',logisticsComplexity:'Baixo',training:'Sim',lastContact:'16 set 2026',address:'São Paulo, SP',contact:{name:'Lara Rodrigues',role:'Suprimentos',phone:'(11) 94398-1184',email:'lara@cliente.com.br'}},
]

export const demoVisits: Visit[] = [
  {id:'v1',clientId:'c1',date:'2026-09-12',time:'10:00',accountManager:'Janderson Souza',status:'Realizada',receivedBy:'Elissandra Dourado',receivedByRole:'Coordenador',relationship:'Excelente',viewedTicketReport:true,hasComplaint:false,notes:'Revisão dos indicadores operacionais e confirmação do plano de treinamento.',nextVisitDate:'2026-10-15'},
  {id:'v2',clientId:'c2',date:'2026-09-08',time:'14:30',accountManager:'Vinícius Gaspar',status:'Realizada',receivedBy:'Diego Viana',receivedByRole:'Gestor',relationship:'Sensível',viewedTicketReport:true,hasComplaint:true,complaint:'Prazo de atendimento',notes:'Alinhado plano de resposta e acompanhamento semanal.',nextVisitDate:'2026-09-22'},
  {id:'v3',clientId:'c5',date:'2026-09-15',time:'09:00',accountManager:'Vinícius Gaspar',status:'Realizada',receivedBy:'Jeovan Barboza',receivedByRole:'Coordenador',relationship:'Excelente',viewedTicketReport:false,hasComplaint:false,notes:'Rotina operacional estável e renovação do cronograma de visitas.',nextVisitDate:'2026-10-20'},
  {id:'v4',clientId:'c8',date:'2026-09-16',time:'11:00',accountManager:'Brandon David',status:'Realizada',receivedBy:'Lara Rodrigues',receivedByRole:'Supervisor',relationship:'Excelente',viewedTicketReport:true,hasComplaint:false,notes:'Apresentação dos resultados do trimestre e próximos marcos.'},
  {id:'v5',clientId:'c3',date:'2026-09-17',time:'10:00',accountManager:'Brandon David',status:'Programada',receivedBy:'—',receivedByRole:'Gestor',relationship:'Sensível',viewedTicketReport:false,hasComplaint:false,notes:''},
  {id:'v6',clientId:'c5',date:'2026-09-18',time:'14:00',accountManager:'Vinícius Gaspar',status:'Programada',receivedBy:'—',receivedByRole:'Coordenador',relationship:'Excelente',viewedTicketReport:false,hasComplaint:false,notes:''},
  {id:'v7',clientId:'c6',date:'2026-09-21',time:'09:30',accountManager:'Carpineli',status:'Programada',receivedBy:'—',receivedByRole:'Supervisor',relationship:'Excelente',viewedTicketReport:false,hasComplaint:false,notes:''},
  {id:'v8',clientId:'c7',date:'2026-09-10',time:'15:00',accountManager:'Evan Cleyton',status:'Atrasada',receivedBy:'—',receivedByRole:'Gestor',relationship:'Crítico',viewedTicketReport:false,hasComplaint:false,notes:''},
  {id:'v9',clientId:'c4',date:'2026-09-23',time:'11:30',accountManager:'Janderson Souza',status:'Programada',receivedBy:'—',receivedByRole:'Coordenador',relationship:'Excelente',viewedTicketReport:false,hasComplaint:false,notes:''},
]
