import type { Client, Visit } from './types'

const report = 'https://vanessarodriguesbr.github.io/painelchamados/'
const base = { status:'Renovado', ticketReportUrl:report, trelloUrl:null, misuseHistory:'Não', training:'Não' } as const

// Conteúdo totalmente fictício. A base real nunca é incorporada ao bundle público.
export const demoClients: Client[] = [
  { ...base,id:'c1',sheetRow:2,startDateFormatted:'12/01/2024',endDateFormatted:'12/01/2027',contractNumber:'DEMO-001',legalName:'EMPRESA DEMONSTRATIVA A LTDA',siteName:'Aurora Center',administrator:'Grupo Exemplo',segment:'Shopping',quantity:4,contractValue:6200,state:'SP',accountManager:'Camila Rocha',relationship:'Excelente',financial:'Adimplente',sla:'72hrs corridas',misuseHistory:'Sim',logisticsComplexity:'Alto',lastContact:'12 set 2026',address:'Endereço ilustrativo — São Paulo, SP',contact:{name:'Ana Martins',role:'Operações',phone:'(00) 90000-0001',email:'ana.martins@example.com'}},
  { ...base,id:'c2',sheetRow:3,startDateFormatted:'23/08/2023',endDateFormatted:'23/08/2027',contractNumber:'DEMO-002',legalName:'EMPRESA DEMONSTRATIVA B LTDA',siteName:'Estação Atlântico',administrator:'Operação Própria',segment:'Condomínio',quantity:1,contractValue:1900,state:'BA',accountManager:'Rafael Lima',relationship:'Sensível',financial:'Inadimplente Crítico',sla:'72hrs úteis',logisticsComplexity:'Médio',lastContact:'08 set 2026',address:'Endereço ilustrativo — Salvador, BA',contact:{name:'Bruno Nunes',role:'Comprador',phone:'(00) 90000-0002',email:'bruno.nunes@example.com'}},
  { ...base,id:'c3',sheetRow:4,startDateFormatted:'29/08/2025',endDateFormatted:'29/08/2027',contractNumber:'DEMO-003',legalName:'EMPRESA DEMONSTRATIVA C LTDA',siteName:'Parque Norte',administrator:'Gestão Modelo',segment:'Condomínio',quantity:1,contractValue:1950,state:'RJ',accountManager:'Bruno Costa',relationship:'Sensível',financial:'Inadimplente Crítico',sla:'48hrs úteis',misuseHistory:'Sim',logisticsComplexity:'Baixo',training:'Sim',lastContact:'04 set 2026',address:'Endereço ilustrativo — Rio de Janeiro, RJ',contact:{name:'Clara Souza',role:'Suprimentos',phone:'(00) 90000-0003',email:'clara.souza@example.com'}},
  { ...base,id:'c4',sheetRow:5,startDateFormatted:'04/07/2025',endDateFormatted:'04/07/2027',contractNumber:'DEMO-004',legalName:'EMPRESA DEMONSTRATIVA D LTDA',siteName:'Shopping Horizonte',administrator:'Rede Ilustrativa',segment:'Shopping',quantity:2,contractValue:3100,state:'AM',accountManager:'Júlia Alves',relationship:'Excelente',financial:'Inadimplente Crítico',sla:'72hrs corridas',logisticsComplexity:'Alto',lastContact:'29 ago 2026',address:'Endereço ilustrativo — Manaus, AM',contact:{name:'Daniel Prado',role:'Operações',phone:'(00) 90000-0004',email:'daniel.prado@example.com'}},
  { ...base,id:'c5',sheetRow:6,startDateFormatted:'08/11/2022',endDateFormatted:'08/11/2027',contractNumber:'DEMO-005',legalName:'EMPRESA DEMONSTRATIVA E LTDA',siteName:'Aeroporto do Sol',administrator:'Aeroportos Exemplo',segment:'Aeroporto',quantity:1,contractValue:2050,state:'PE',accountManager:'Rafael Lima',relationship:'Excelente',financial:'Adimplente',sla:'Sem menção',logisticsComplexity:'Médio',lastContact:'15 set 2026',address:'Endereço ilustrativo — Recife, PE',contact:{name:'Elisa Barros',role:'Coordenadora Administrativa',phone:'(00) 90000-0005',email:'elisa.barros@example.com'}},
  { ...base,id:'c6',sheetRow:7,startDateFormatted:'19/04/2021',endDateFormatted:'19/04/2027',contractNumber:'DEMO-006',legalName:'EMPRESA DEMONSTRATIVA F LTDA',siteName:'Via Verde Empresarial',administrator:'Aliança Modelo',segment:'Shopping',quantity:1,contractValue:2250,state:'MG',accountManager:'Camila Rocha',relationship:'Excelente',financial:'Adimplente',sla:'72hrs úteis',logisticsComplexity:'Alto',lastContact:'10 set 2026',address:'Endereço ilustrativo — Belo Horizonte, MG',contact:{name:'Felipe Moraes',role:'Operações',phone:'(00) 90000-0006',email:'felipe.moraes@example.com'}},
  { ...base,id:'c7',sheetRow:8,startDateFormatted:'04/10/2021',endDateFormatted:'04/10/2027',contractNumber:'DEMO-007',legalName:'EMPRESA DEMONSTRATIVA G LTDA',siteName:'Boulevard Central',administrator:'Rede Ilustrativa',segment:'Shopping',quantity:1,contractValue:1600,state:'CE',accountManager:'Júlia Alves',relationship:'Crítico',financial:'Inadimplência Moderada',sla:'72hrs corridas',logisticsComplexity:'Médio',lastContact:'21 ago 2026',address:'Endereço ilustrativo — Fortaleza, CE',contact:{name:'Gabriel Freitas',role:'Gerente de Operações',phone:'(00) 90000-0007',email:'gabriel.freitas@example.com'}},
  { ...base,id:'c8',sheetRow:9,startDateFormatted:'23/09/2022',endDateFormatted:'23/09/2027',contractNumber:'DEMO-008',legalName:'EMPRESA DEMONSTRATIVA H LTDA',siteName:'Linha Urbana',administrator:'Mobilidade Modelo',segment:'Metrô',quantity:2,contractValue:4000,state:'DF',accountManager:'Bruno Costa',relationship:'Excelente',financial:'Adimplente',sla:'48hrs corridas',misuseHistory:'Sim',logisticsComplexity:'Baixo',training:'Sim',lastContact:'16 set 2026',address:'Endereço ilustrativo — Brasília, DF',contact:{name:'Helena Duarte',role:'Suprimentos',phone:'(00) 90000-0008',email:'helena.duarte@example.com'}},
]

export const demoVisits: Visit[] = [
  {id:'v1',clientId:'c1',date:'2026-09-12',time:'10:00',accountManager:'Camila Rocha',status:'Realizada',receivedBy:'Ana Martins',receivedByRole:'Coordenador',relationship:'Excelente',viewedTicketReport:true,hasComplaint:false,notes:'Revisão dos indicadores operacionais e confirmação do plano de treinamento.',nextVisitDate:'2026-10-15'},
  {id:'v2',clientId:'c2',date:'2026-09-08',time:'14:30',accountManager:'Rafael Lima',status:'Realizada',receivedBy:'Bruno Nunes',receivedByRole:'Gestor',relationship:'Sensível',viewedTicketReport:true,hasComplaint:true,complaint:'Prazo de atendimento',notes:'Alinhado plano de resposta e acompanhamento semanal.',nextVisitDate:'2026-09-22'},
  {id:'v3',clientId:'c5',date:'2026-09-15',time:'09:00',accountManager:'Rafael Lima',status:'Realizada',receivedBy:'Elisa Barros',receivedByRole:'Coordenador',relationship:'Excelente',viewedTicketReport:false,hasComplaint:false,notes:'Rotina operacional estável e renovação do cronograma de visitas.',nextVisitDate:'2026-10-20'},
  {id:'v4',clientId:'c8',date:'2026-09-16',time:'11:00',accountManager:'Bruno Costa',status:'Realizada',receivedBy:'Helena Duarte',receivedByRole:'Supervisor',relationship:'Excelente',viewedTicketReport:true,hasComplaint:false,notes:'Apresentação dos resultados do trimestre e próximos marcos.'},
  {id:'v5',clientId:'c3',date:'2026-09-17',time:'10:00',accountManager:'Bruno Costa',status:'Programada',receivedBy:'A confirmar',receivedByRole:'Gestor',relationship:'Sensível',viewedTicketReport:false,hasComplaint:false,notes:''},
  {id:'v6',clientId:'c5',date:'2026-09-18',time:'14:00',accountManager:'Rafael Lima',status:'Programada',receivedBy:'A confirmar',receivedByRole:'Coordenador',relationship:'Excelente',viewedTicketReport:false,hasComplaint:false,notes:''},
  {id:'v7',clientId:'c6',date:'2026-09-21',time:'09:30',accountManager:'Camila Rocha',status:'Programada',receivedBy:'A confirmar',receivedByRole:'Supervisor',relationship:'Excelente',viewedTicketReport:false,hasComplaint:false,notes:''},
  {id:'v8',clientId:'c7',date:'2026-09-10',time:'15:00',accountManager:'Júlia Alves',status:'Atrasada',receivedBy:'A confirmar',receivedByRole:'Gestor',relationship:'Crítico',viewedTicketReport:false,hasComplaint:false,notes:''},
  {id:'v9',clientId:'c4',date:'2026-09-23',time:'11:30',accountManager:'Júlia Alves',status:'Programada',receivedBy:'A confirmar',receivedByRole:'Coordenador',relationship:'Excelente',viewedTicketReport:false,hasComplaint:false,notes:''},
]
